### PR TITLE
CB-9426 Fix exception using device motion plugin on browser platform

### PR DESCRIPTION
**Pull request by TimBarham**
The plugin's `plugin.xml` defines a general `<js-module>` with the name `accelerometer`. It defines another `<js-module>` for the `browser` platform with the same name. Modules with the same name are not allowed, so Cordova throws an exception at runtime when trying to define the browser version of the module.

Since the only difference in the `browser` version of the module is to fake up `devicemotion` events, I've deleted the browser version and added that logic to the general module, with the following change: rather than starting a new event timer every time `watchAcceleration()` is called (which could happen multiple times resulting in multiple superfluous timers), we have a single event timer going as long as there are active watchers.

### CODE REVIEW

**Comment by TimBarham** [comment]
@stevengill and @purplecabbage - interested in whether this fix looks right to you guys, since I've not worked in this code much before. Certainly after my change the functionality seems correct - the `browser` specific module is a merge, with the same target that the general module clobbers. Without my change, we don't get the merge. With my change, I verified we do.

**Comment by purplecabbage** [comment]
LGTM!

**Comment by purplecabbage** [comment]
Actually, on second thought ...
I don't think there is much reason for the browser implementation to have it's own version of accelerometer.js This file is virtually identical to the one at www/accelerometer.js so maybe it is time for a quick refactor.  

Your understanding of merges and uniqueness of name are correct though. ;)

**Comment by TimBarham** [comment]
Yeah, I have just been wondering the same thing. The only `browser` specific thing is that it starts firing the `devicemotion` event when you call `watchAcceleration()` (and turns it off when you call `clearWatch()`) - that could easily be included in the general `accelerometer.js`.

**Comment by TimBarham** [comment]
Ok, I've deleted the browser specific implementation and moved the browser specific logic into the general implementation, and also added some logic to avoid multiple event timers being triggered.

**Comment by vladimir-kotikov** [comment]
The PR LGTM.

However, IMO the code that emits `devicemotion` events might be removed due to:
  a) this is not a scope of plugin to provide stubs for browser functionality
  b) the `devicemotion` event is already supported by most of the browsers (http://caniuse.com/#search=devicemotion).

@purplecabbage, what do you think?

**Comment by purplecabbage** [comment]
Yeah. I was still going to look at a rewrite in the near future. No need to fake data...

**Comment by TimBarham** [comment]
I agree. My goal here however was just to fix the exception, not change the behavior of a plugin I'm not familiar with :smile:... So what's the consensus - should I merge this change now, or just leave it pendinging @purplecabbage's rewrite (same question applies to the `device-orientation` change as well).

**Comment by purplecabbage** [comment]
Yeah. Merge as is to side step the error. 
I'll create jira tickets and revisit later.

**Pull request merged**
